{{- if .Values.clusterAgent.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "floor.clusterAgent.fullname" . }}
  labels:
    {{- include "floor.clusterAgent.selectorLabels" . | nindent 4 }}
{{- end }}
