apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "floor.fullname" . }}-migrate
  labels:
    {{- include "floor.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "1"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        {{- include "floor.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migrate
    spec:
      restartPolicy: Never
      {{- include "floor.imagePullSecrets" . | nindent 6 }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: migrate
          image: {{ include "floor.image" . }}
          command: ["node", "packages/store/dist/migrate-cli.js"]
          env:
            - name: FLOOR_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "floor.postgres.secretName" . }}
                  key: {{ include "floor.postgres.secretKey" . }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
